CREATE TABLE IF NOT EXISTS orders (
    id BIGINT PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    sku_id BIGINT,
    product_name VARCHAR(128) NOT NULL,
    unit_price NUMERIC(18, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    address_id BIGINT,
    recipient_name VARCHAR(64),
    recipient_phone VARCHAR(32),
    province VARCHAR(64),
    city VARCHAR(64),
    district VARCHAR(64),
    address_detail VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_orders_order_no ON orders (order_no);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_create_time ON orders (create_time);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    sku_id BIGINT,
    product_name VARCHAR(128) NOT NULL,
    unit_price NUMERIC(18, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);

CREATE TABLE IF NOT EXISTS order_inventory_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    reservation_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_order_inventory_reservations_order_id ON order_inventory_reservations (order_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_order_inventory_reservation_id ON order_inventory_reservations (reservation_id);

CREATE TABLE IF NOT EXISTS order_status_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32) NOT NULL,
    reason VARCHAR(255),
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_order_status_logs_order_id ON order_status_logs (order_id);

CREATE TABLE IF NOT EXISTS order_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR(128) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    next_retry_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_order_outbox_events_event_key ON order_outbox_events (event_key);
CREATE INDEX IF NOT EXISTS idx_order_outbox_events_status_retry ON order_outbox_events (status, next_retry_time);
