CREATE TABLE IF NOT EXISTS order_sub_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkout_order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    sku_id BIGINT,
    product_name VARCHAR(128) NOT NULL,
    unit_price NUMERIC(18, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    merchant_id BIGINT,
    status VARCHAR(32) NOT NULL,
    refund_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_order_sub_orders_checkout_order_id ON order_sub_orders (checkout_order_id);
CREATE INDEX IF NOT EXISTS idx_order_sub_orders_status ON order_sub_orders (status);

CREATE TABLE IF NOT EXISTS order_refund_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_request_no VARCHAR(64) NOT NULL UNIQUE,
    checkout_order_id BIGINT NOT NULL,
    sub_order_id BIGINT,
    refund_amount NUMERIC(18, 2) NOT NULL,
    reason VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    raw_response TEXT,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_order_refund_requests_checkout_order_id ON order_refund_requests (checkout_order_id);
CREATE INDEX IF NOT EXISTS idx_order_refund_requests_sub_order_id ON order_refund_requests (sub_order_id);
CREATE INDEX IF NOT EXISTS idx_order_refund_requests_status ON order_refund_requests (status);
