CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(64) NOT NULL,
    second_name VARCHAR(64) NOT NULL,
    phone VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(128) NOT NULL UNIQUE,
    default_address_slot_id BIGINT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_credentials (
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(128) NOT NULL,
    password_salt VARCHAR(128) NOT NULL,
    password_algorithm VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(128) NOT NULL UNIQUE,
    resource VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    assigned_by BIGINT,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(id),
    permission_id BIGINT NOT NULL REFERENCES permissions(id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    assigned_by BIGINT,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_address_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    address_id BIGINT NOT NULL,
    slot_name VARCHAR(64) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO users (id, first_name, second_name, phone, email, default_address_slot_id, enabled, deleted)
VALUES
    (1, 'Platform', 'Admin', '13800000001', 'admin@demo.local', NULL, TRUE, FALSE),
    (2, 'Demo', 'Customer', '13800000002', 'customer@demo.local', NULL, TRUE, FALSE),
    (3, 'Demo', 'Merchant', '13800000003', 'merchant@demo.local', NULL, TRUE, FALSE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO user_credentials (user_id, username, password_hash, password_salt, password_algorithm)
VALUES
    (1, 'admin', '196a89d9d0f770ef1e37c02dc8ca495402673540c2dfac817c6533c79e85030b', 'commerce-admin-salt', 'SHA-256'),
    (2, 'customer', 'cd6ff74bddc9ebacd473fc9116a20daf69b4d2856af7bf91e384638bffcd62a2', 'commerce-customer-salt', 'SHA-256'),
    (3, 'merchant', 'ee56ceb4c6f8a26a0fa5ef639b33346d9806e795e35cb8c45532a164a39e0d9e', 'commerce-merchant-salt', 'SHA-256')
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO roles (id, code, name, description)
VALUES
    (1, 'ADMIN', 'Administrator', 'Platform administrator'),
    (2, 'CUSTOMER', 'Customer', 'Commerce customer'),
    (3, 'MERCHANT', 'Merchant', 'Commerce merchant')
ON CONFLICT (id) DO NOTHING;

INSERT INTO permissions (id, code, resource, action, name, description)
VALUES
    (1, 'order:create', 'order', 'create', 'Create order', 'Create commerce orders'),
    (2, 'order:view', 'order', 'view', 'View order', 'View commerce orders'),
    (3, 'payment:pay', 'payment', 'pay', 'Pay order', 'Pay for commerce orders'),
    (4, 'inventory:view', 'inventory', 'view', 'View inventory', 'View product inventory'),
    (5, 'inventory:update', 'inventory', 'update', 'Update inventory', 'Update product inventory'),
    (6, 'product:view', 'product', 'view', 'View product', 'View product catalog'),
    (7, 'product:create', 'product', 'create', 'Create product', 'Create products'),
    (8, 'product:update', 'product', 'update', 'Update product', 'Update products'),
    (9, 'user:view', 'user', 'view', 'View user', 'View users'),
    (10, 'notification:send', 'notification', 'send', 'Send notification', 'Send notifications'),
    (11, 'address:view', 'address', 'view', 'View address', 'View addresses')
ON CONFLICT (id) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
VALUES
    (1, 1),
    (2, 2),
    (3, 3)
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
VALUES
    (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11),
    (2, 1), (2, 2), (2, 3), (2, 6), (2, 11),
    (3, 2), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 11)
ON CONFLICT (role_id, permission_id) DO NOTHING;
