CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(64) NOT NULL,
    second_name VARCHAR(64) NOT NULL,
    phone VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(128) NOT NULL UNIQUE,
    default_address_id BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO users (id, first_name, second_name, phone, email, default_address_id, deleted)
VALUES
    (1, 'Platform', 'Admin', '13800000001', 'admin@demo.local', NULL, FALSE),
    (2, 'Demo', 'Customer', '13800000002', 'customer@demo.local', NULL, FALSE),
    (3, 'Demo', 'Merchant', '13800000003', 'merchant@demo.local', NULL, FALSE)
ON CONFLICT (id) DO NOTHING;
