server:
  port: 8085

spring:
  application:
    name: psj-commerce-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/psj_commerce_payment
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
