apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: commerce-dev

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - infra.yaml
  - postgres.yaml
  - apps.yaml
