CREATE TABLE IF NOT EXISTS inv_warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500),
    manager BIGINT,
    phone VARCHAR(64),
    description VARCHAR(1000),
    disable BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inv_bins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL REFERENCES inv_warehouses(id),
    name VARCHAR(255) NOT NULL,
    zone VARCHAR(255) NOT NULL,
    "row" VARCHAR(255) NOT NULL,
    col VARCHAR(255) NOT NULL,
    level VARCHAR(255) NOT NULL,
    slot VARCHAR(255) NOT NULL,
    bin_type VARCHAR(50) NOT NULL,
    remark VARCHAR(1000),
    disable BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    disable_time TIMESTAMPTZ,
    CONSTRAINT uk_inv_bins_warehouse_location UNIQUE (warehouse_id, zone, "row", col, level, slot)
);

CREATE TABLE IF NOT EXISTS inv_warehouse_default_bin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL REFERENCES inv_warehouses(id),
    bin_id BIGINT NOT NULL REFERENCES inv_bins(id),
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_inv_warehouse_default_bin UNIQUE (warehouse_id, bin_id)
);

CREATE TABLE IF NOT EXISTS inv_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL REFERENCES inv_warehouses(id),
    available_qty BIGINT NOT NULL DEFAULT 0,
    available_lock_qty BIGINT NOT NULL DEFAULT 0,
    defective_qty BIGINT NOT NULL DEFAULT 0,
    defective_lock_qty BIGINT NOT NULL DEFAULT 0,
    to_inspection_qty BIGINT NOT NULL DEFAULT 0,
    transfer_in_transit BIGINT NOT NULL DEFAULT 0,
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_inv_balances_sku_warehouse UNIQUE (sku_id, warehouse_id)
);

CREATE TABLE IF NOT EXISTS inv_bin_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id BIGINT NOT NULL,
    bin_id BIGINT NOT NULL REFERENCES inv_bins(id),
    quantity BIGINT NOT NULL DEFAULT 0,
    lock_qty BIGINT NOT NULL DEFAULT 0,
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_inv_bin_balances_sku_bin UNIQUE (sku_id, bin_id)
);

CREATE TABLE IF NOT EXISTS inv_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL REFERENCES inv_warehouses(id),
    bin_id BIGINT NOT NULL REFERENCES inv_bins(id),
    parent_reservation_id BIGINT,
    transaction_id BIGINT,
    reserved BIGINT NOT NULL DEFAULT 0,
    consumed BIGINT NOT NULL DEFAULT 0,
    released BIGINT NOT NULL DEFAULT 0,
    remaining BIGINT NOT NULL DEFAULT 0,
    available_from TIMESTAMPTZ,
    available_to TIMESTAMPTZ,
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cancelled_time TIMESTAMPTZ,
    released_time TIMESTAMPTZ,
    remark VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS inv_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_order_id BIGINT NOT NULL,
    linked_order_ids BIGINT[] NOT NULL DEFAULT '{}',
    transaction_type VARCHAR(64) NOT NULL,
    operator_id BIGINT NOT NULL,
    remark VARCHAR(1000),
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cancelled_time TIMESTAMPTZ,
    completed_time TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS inv_warehouse_ledgers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL REFERENCES inv_warehouses(id),
    warehouse_ledger_type VARCHAR(64) NOT NULL,
    available_delta BIGINT NOT NULL,
    available_lock_delta BIGINT NOT NULL,
    defective_delta BIGINT NOT NULL,
    defective_lock_delta BIGINT NOT NULL,
    to_inspection_delta BIGINT NOT NULL,
    transfer_in_transit_delta BIGINT NOT NULL,
    available_balance BIGINT NOT NULL,
    available_lock_balance BIGINT NOT NULL,
    defective_balance BIGINT NOT NULL,
    defective_lock_balance BIGINT NOT NULL,
    to_inspection_balance BIGINT NOT NULL,
    transfer_in_transit_balance BIGINT NOT NULL,
    transaction_id BIGINT NOT NULL REFERENCES inv_transactions(id),
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    remark VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS inv_bin_ledgers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT,
    sku_id BIGINT NOT NULL,
    bin_id BIGINT NOT NULL REFERENCES inv_bins(id),
    bin_ledger_type VARCHAR(64) NOT NULL,
    delta BIGINT NOT NULL,
    lock_delta BIGINT NOT NULL,
    balance BIGINT NOT NULL,
    lock_balance BIGINT NOT NULL,
    transaction_id BIGINT NOT NULL REFERENCES inv_transactions(id),
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    remark VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS inv_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(64) NOT NULL UNIQUE,
    type_key VARCHAR(64) NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creator BIGINT NOT NULL,
    delete_time TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS inv_receipt_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT NOT NULL REFERENCES inv_receipts(id),
    state VARCHAR(64) NOT NULL,
    payload JSONB NOT NULL,
    operator BIGINT NOT NULL,
    record_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    disable_time TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS inv_sequence_numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number_type VARCHAR(50) NOT NULL,
    date_key VARCHAR(50) NOT NULL,
    current_sequence INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_inv_sequence_numbers_type_date UNIQUE (number_type, date_key)
);

CREATE INDEX IF NOT EXISTS idx_inv_balances_sku_id ON inv_balances (sku_id);
CREATE INDEX IF NOT EXISTS idx_inv_bin_balances_sku_id ON inv_bin_balances (sku_id);
CREATE INDEX IF NOT EXISTS idx_inv_reservations_sku_id ON inv_reservations (sku_id);
CREATE INDEX IF NOT EXISTS idx_inv_reservations_transaction_id ON inv_reservations (transaction_id);
CREATE INDEX IF NOT EXISTS idx_inv_warehouse_ledgers_time_sku ON inv_warehouse_ledgers (created_time, sku_id);
CREATE INDEX IF NOT EXISTS idx_inv_bin_ledgers_time_sku_bin ON inv_bin_ledgers (created_time, sku_id, bin_id);
CREATE INDEX IF NOT EXISTS idx_inv_receipt_records_receipt_id ON inv_receipt_records (receipt_id);
CREATE INDEX IF NOT EXISTS idx_inv_receipt_records_current ON inv_receipt_records (receipt_id, disable_time);
