server:
  port: 8086

spring:
  application:
    name: commerce-notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: false
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce_notification
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
