CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    price NUMERIC(18, 2) NOT NULL,
    sku_id BIGINT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_sku_id ON products (sku_id);
CREATE INDEX IF NOT EXISTS idx_products_enabled_deleted ON products (enabled, deleted);

INSERT INTO products (id, name, price, sku_id, enabled, deleted)
VALUES (1, 'Demo Product', 99.00, 1, TRUE, FALSE)
ON CONFLICT (id) DO NOTHING;
