server:
  port: 8080

spring:
  application:
    name: psj-demo-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: psj-demo-consumer
          uri: lb://psj-demo-consumer
          predicates:
            - Path=/hello/**
