server:
  port: 8085

spring:
  application:
    name: commerce-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce_payment
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

payment:
  order-timeout-minutes: 30
  alipay:
    gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    app-id: 9021000165603108
    app-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChRpMlZCkgpfXg8bR34Uhb8cgCTcm8suAnzSQptBIoeNoiqbgmNYYpYXEPWB0Md3J8J3YDvfH69UezS1jiCLG/6uzUwu1RgK1+Wq784CLv9JjySPO/ENgxIWaVXGs/dC265Edh5Es7riIye7baTaVZDjjZi0KaaDO/FIFieIBAaA7TySkn9hn3afVJbyEgyb2t/XFWtLP/q63MPM30o/zzcW4invXdq2dSG5BhDXB1A55oilQeLq5r1SMSb4aWL3cOg2rZ3OBWSBQkK8pXfFVxtMsZNjJVlB1BgpAEvfXHAJg5i8MGex8pJEJA9iUCC9/Yeg1TrSCzfUzKQiU8Wt/FAgMBAAECggEAetXCJWyQVqmRCO+PwO75qe4RpI+S5AJp8Gay8ICSg/joTBZwh8mkkcgB0OoP1fr0W9PCcz8tGzPOlKUC4cY1fDN2huag0r7rZZ20Qi6E7bai94bQ/+nYgDMsav6lQQNAAWT1aX30P1R1/3Vy4/rXwWivrCIBbJGJODRqB5I4PNTOxUOhePCJVmktHEEwKOqXd84oIqBi7c8N7tfpO191CQn5Vh+pv+gFcJJaHWvCQltBz8vBBoyUlT/dJr+t1YowxuJFk0/FOm+z/8entRhVdtNNz4bGcpVkYP8qksaInWVcUUV2og/sflwsEwQs0n/AypMOoBu3MG4ZnaH4FGNT0QKBgQDXlTEoVTdejmuEbPoENg+bMQyr1XWS8lhJpBNs+oQh8K72RRBH8y/Jm2xiT9lK4aqlcEH4y6L/6hj7MbbZhJfV2jjmiPOe65ZMrUb4Vt7Ap43nZU4En8B9KSfQF1+zwtaDePyLjZUCK1gF7ZiGc7bAoVxRJZt3dhjLVg00l6HxmwKBgQC/gu+GPxJWXHzae5jOVfEsTVvweokjJ15zKeqaqtpe9Q+hpyXZ4XKKsZPHhD08f/lf0E/74JmdjW0KKNNSQ/SHH/dUDtPA7GHSYXp/GX/Xtk97/NU2i4bTFPOQbSBo7ry1rLZ7W2gPLGc6/xILfp2P6OpxWPPl8P14t1UOj9y6HwKBgQCxkcyMuSxDMTH0QMLqhxDxtkQGoWsXn5ADECeEAxCk2Bd098wCR5fcCq4KiFSlrh0d6codQLZA7rSm6vr+TY228ukdUj7AbrI89BjZ4svVie2DZFkPy/oD3ctSRn5olZqVbikuVW8f+02kjGCulk84eXCN0lks29RuX7G+2Qrl8wKBgB4srTzDt0nwLKPoEX2BQQyv66qKRA1L6K/QjOxtuxZ3Gk1oHqijwv5jWFt5VISxzULxeYjALLQMUn/lStaNanvX54pRA8BD/m29eiWIiQId8YwhnB6KAWZEyNOavh6KbyVY3y+0iULKxkEfa2JwQrcoBbhyQYubWvSoPjibJjYVAoGBAK2J56G9xdGWH/AtWRPr9uHJXwr/CflR4jxRskC5urM17nrIL1GejsikfMvFHAJ/nQntDIT2G1zaC5O4JTnngfWVl/AX1zzKHiHPShc9l8FdmW/1i2ftnPHmj++O5o+8nWlaJA4Ac7Ze2Rzm+4DDyfkUraGqNYozKuflQo3+80I+
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoN4YTRI0bHfPO/39s1vPEVgCpk2dvAtTqU7jaHExE4ZDFxfEa/vnnZq/whNRJrUWET9/5piYIogZXzDsppFilZsHdrn8lWRl/kuej2r2oyyFthMTWlB4WauDKBIAAgnw0fVr/S2bYTSXo42ahBHnsjXW3lAz1rgpihd7R0P0l2wN/VUK8zHddo03aJNHAAwscZSpnDKdL0vCnQm+iACF6HQxD+VU44lbZr8ccltrZ9t53dHgLBBwh3qrL3Uua1Au7/pubnyf8B+poZ+PYaG0okwDSUR22sWCZIAzzjXGDY4laPhIF4O6hz73NPjw8dCTWOgbmcYxdJ69XYNqOYzvkQIDAQAB
    notify-url:
mybatis:
  type-handlers-package: com.commerce.mybatis
