package com.commerce.agent.application.harness;

public enum AgentEventType {
	RUN_QUEUED, RUN_STARTED, SESSION_LOCKED, ROUTE_SELECTED, MODEL_STARTED, TOOL_STARTED, TOOL_COMPLETED, TOOL_FAILED, MODEL_COMPLETED, RUN_SUCCEEDED, RUN_FAILED, RUN_CANCEL_REQUESTED, RUN_CANCELLED, RUN_TIMED_OUT
}
