CREATE TABLE IF NOT EXISTS notification_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    user_id BIGINT,
    template_code VARCHAR(64) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    recipient VARCHAR(128),
    payload TEXT,
    status VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    sent_time TIMESTAMPTZ,
    error_message TEXT,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_notification_records_idempotency_key ON notification_records (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_notification_records_order_id ON notification_records (order_id);
CREATE INDEX IF NOT EXISTS idx_notification_records_status ON notification_records (status);
