CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recipient_name VARCHAR(64) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    province VARCHAR(64) NOT NULL,
    city VARCHAR(64) NOT NULL,
    district VARCHAR(64) NOT NULL,
    detail VARCHAR(255) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses (user_id);
CREATE INDEX IF NOT EXISTS idx_addresses_user_default ON addresses (user_id, is_default, deleted);

INSERT INTO addresses (
    id,
    user_id,
    recipient_name,
    phone,
    province,
    city,
    district,
    detail,
    is_default,
    deleted
) VALUES (
    1,
    1,
    'Demo User',
    '13800000000',
    'Shanghai',
    'Shanghai',
    'Pudong',
    'Pudong New Area 1001',
    TRUE,
    FALSE
) ON CONFLICT (id) DO NOTHING;
