CREATE TABLE IF NOT EXISTS payment_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkout_order_id BIGINT NOT NULL UNIQUE,
    out_trade_no VARCHAR(64) NOT NULL UNIQUE,
    trade_no VARCHAR(64),
    amount NUMERIC(18, 2) NOT NULL,
    subject VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    raw_response TEXT,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id BIGINT NOT NULL REFERENCES payment_order(id),
    checkout_order_id BIGINT NOT NULL,
    sub_order_id BIGINT NOT NULL,
    merchant_id BIGINT,
    goods_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    shipping_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    platform_discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    merchant_discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    paid_amount NUMERIC(18, 2) NOT NULL,
    settle_amount NUMERIC(18, 2) NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (payment_order_id, sub_order_id)
);

CREATE TABLE IF NOT EXISTS payment_notify_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notify_id VARCHAR(64),
    out_trade_no VARCHAR(64),
    trade_status VARCHAR(32),
    verified BOOLEAN NOT NULL,
    payload TEXT NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id BIGINT NOT NULL REFERENCES payment_order(id),
    checkout_order_id BIGINT NOT NULL,
    out_trade_no VARCHAR(64) NOT NULL,
    out_refund_no VARCHAR(64) NOT NULL UNIQUE,
    refund_amount NUMERIC(18, 2) NOT NULL,
    status VARCHAR(32) NOT NULL,
    raw_response TEXT,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_refund_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_refund_id BIGINT NOT NULL REFERENCES payment_refund(id),
    payment_allocation_id BIGINT REFERENCES payment_allocation(id),
    checkout_order_id BIGINT NOT NULL,
    sub_order_id BIGINT NOT NULL,
    merchant_id BIGINT,
    refund_goods_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    refund_shipping_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    refund_platform_discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    refund_merchant_discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    refund_paid_amount NUMERIC(18, 2) NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_reconcile_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_date DATE NOT NULL,
    bill_type VARCHAR(32) NOT NULL,
    download_url TEXT,
    status VARCHAR(32) NOT NULL,
    raw_response TEXT,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (bill_date, bill_type)
);

CREATE TABLE IF NOT EXISTS idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(128) NOT NULL UNIQUE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
