CREATE TABLE IF NOT EXISTS payment_reconcile_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_date DATE NOT NULL,
    bill_type VARCHAR(32) NOT NULL,
    out_trade_no VARCHAR(64),
    trade_no VARCHAR(64),
    out_refund_no VARCHAR(64),
    amount NUMERIC(18, 2),
    trade_status VARCHAR(64),
    raw_line TEXT NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payment_reconcile_detail_bill ON payment_reconcile_detail (bill_date, bill_type);
CREATE INDEX IF NOT EXISTS idx_payment_reconcile_detail_trade ON payment_reconcile_detail (out_trade_no);
CREATE INDEX IF NOT EXISTS idx_payment_reconcile_detail_refund ON payment_reconcile_detail (out_refund_no);

CREATE TABLE IF NOT EXISTS payment_reconcile_diff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_date DATE NOT NULL,
    bill_type VARCHAR(32) NOT NULL,
    diff_type VARCHAR(64) NOT NULL,
    out_trade_no VARCHAR(64),
    out_refund_no VARCHAR(64),
    local_status VARCHAR(64),
    channel_status VARCHAR(64),
    local_amount NUMERIC(18, 2),
    channel_amount NUMERIC(18, 2),
    detail TEXT,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payment_reconcile_diff_bill ON payment_reconcile_diff (bill_date, bill_type);
CREATE INDEX IF NOT EXISTS idx_payment_reconcile_diff_type ON payment_reconcile_diff (diff_type);
